# Generated by Django 4.1.4 on 2023-02-03 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subsribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
