# Generated by Django 4.1.4 on 2023-02-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_subsribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
